Genre.find_or_create_by(tmdb_id: 28, name: "Action")
Genre.find_or_create_by(tmdb_id: 12, name: "Adventure")
Genre.find_or_create_by(tmdb_id: 16, name: "Animation")
Genre.find_or_create_by(tmdb_id: 35, name: "Comedy")
Genre.find_or_create_by(tmdb_id: 80, name: "Crime")
Genre.find_or_create_by(tmdb_id: 99, name: "Documentary")
Genre.find_or_create_by(tmdb_id: 18, name: "Drama")
Genre.find_or_create_by(tmdb_id: 10751, name: "Family")
Genre.find_or_create_by(tmdb_id: 14, name: "Fantasy")
Genre.find_or_create_by(tmdb_id: 36, name: "History")
Genre.find_or_create_by(tmdb_id: 27, name: "Horror")
Genre.find_or_create_by(tmdb_id: 10402, name: "Music")
Genre.find_or_create_by(tmdb_id: 9648, name: "Mystery")
Genre.find_or_create_by(tmdb_id: 10749, name: "Romance")
Genre.find_or_create_by(tmdb_id: 878, name: "Science Fiction")
Genre.find_or_create_by(tmdb_id: 10770, name: "TV Movie")
Genre.find_or_create_by(tmdb_id: 53, name: "Thriller")
Genre.find_or_create_by(tmdb_id: 10752, name: "War")
Genre.find_or_create_by(tmdb_id: 37, name: "Western")
